name: test (python 2.7)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python: python2
            pip: pip
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install -y python2

      - name: Install npm dependencies
        run: |
          npm install buffer-shims
          npm install --global rollup

      - name: Install python dependencies
        run: |
          wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
          ${{ matrix.python }} get-pip.py
          ${{ matrix.python }} -m ${{ matrix.pip }} install --user --upgrade pip
          ${{ matrix.python }} -m ${{ matrix.pip }} --no-cache-dir install --user -e .[tests,docs]

      - name: Show python dependencies
        run: |
          ${{matrix.pip}} --version
          ${{ matrix.python }} --version
          ${{ matrix.pip }} freeze

      - name: Build Test
        run: |
          ./tests/integration/test_setup.sh ${{ matrix.python }}

      - name: Run tests
        run: |
          ./run-tests.sh
