name: Build and release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [2.7, 3.6]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 10.14.0
          registry-url: 'https://registry.npmjs.org'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install npm dependencies
        run: |
          npm install buffer-shims
          npm install --global rollup

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel "urllib3==1.25.11"
          pip install -e .[tests,docs]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh

      - name: Build package
        if: ${{ success() && github.event_name == 'push' && matrix.python-version == '2.7'  }}
        run: |
          mkdir clean-build
          python setup.py sdist bdist_wheel --universal --dist-dir ./clean-build

      - name: Publish package
        if: ${{ success() && github.event_name == 'push' && matrix.python-version == '2.7'  }}
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          verify_metadata: false
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: clean-build/

      - name: Build npm package
        if: ${{ success() && github.event_name == 'push' && matrix.python-version == '2.7'  }}
        run: |
          npm install --dev
          npm run build

      - name: Version npm package
        if: ${{ success() && github.event_name == 'push' && matrix.python-version == '2.7'  }}
        run: |
          npm version $(git describe --always --tags) --no-git-tag-version

      - name: Publish npm package
        if: ${{ success() && github.event_name == 'push' && matrix.python-version == '2.7'  }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
