name: test (python 2.7)

on:
  push:
    branches: [py-2]
  pull_request:
    branches: [py-2]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [python2.7]
        pip: [pip2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install npm dependencies
        run: |
          npm install buffer-shims
          npm install --global rollup

      - name: Install python dependencies
        run: |
          ${{ matrix.pip }} install --user --upgrade pip
          ${{ matrix.pip }} --no-cache-dir install --user -e .[tests,docs]

      - name: Show python dependencies
        run: |
          ${{ matrix.python }} --version
          ${{ matrix.pip }} freeze

      - name: Run tests
        run: |
          ./run-tests.sh
